"""Refuse to let anything that looks like a medical image into this repository.

One implementation, four callers:

    python .githooks/scan_staged.py             # the index (pre-commit)
    python .githooks/scan_staged.py --history   # every blob ever committed (pre-push, CI)
    python .githooks/scan_staged.py --paths a b # named files

That matters more than it sounds. This check previously existed twice — a
thorough version in the hook, and a weaker one written separately in the CI
workflow that looked only for a part-10 preamble. The weak copy was the one
that always ran, because a hook is opt-in and CI is not, so the mandatory gate
was the one that missed raw DICOM. Two copies of a rule drift, and the copy
that drifts is found by the thing it was supposed to prevent.

Identification is by content wherever possible. A DICOM file named `notes.dat`
is still a DICOM file, and an extension filter waves it through.

Two properties this scanner has to have, and did not:

* **It reads what git is about to commit, not what is on disk.** These differ,
  and the ordinary way they differ is not adversarial: `git add .` picks up an
  export, you delete the file, you commit. The deletion did not touch the
  index. Reading the worktree found nothing to look at and said so by saying
  nothing at all.
* **It cannot be switched off by a filename.** Git quotes any path outside
  ASCII — `ผู้ป่วย/scan.dcm` arrives as `"\340\270\234..."` — which no longer
  named a file that could be opened, and the loop skipped it in silence. On a
  project written in Thailand that is not an edge case; it is Tuesday. Every
  git command here therefore uses `-z`, and nothing is ever skipped quietly.

Every rule below that is not obvious was added because red-teaming this
scanner got a synthetic file past the previous version of it.

A guard that fails open is worse than no guard, because the project keeps
relying on it. This one exits non-zero on any error it did not expect, reports
anything it could not check as a refusal rather than a pass, and
tests/test_hook.py stages decoys against it on every commit.
"""

from __future__ import annotations

import argparse
import os
import re
import subprocess
import sys

MEDICAL = {".dcm", ".ima", ".dicom", ".img", ".nii", ".mha", ".mhd",
           ".raw", ".hdr", ".zraw", ".iso", ".nrrd", ".analyze"}

PREAMBLE = b"DICM"              # part-10, at offset 128
UID_STEM = b"1.2.840.10008"     # the DICOM UID root — all of them, not just pixel syntaxes
LFS_POINTER = b"version https://git-lfs.github.com/spec/v1"

# A blob this large is not something this project commits, and reading it in
# full to check it costs more than refusing it. Unchecked is refused, so the
# limit cannot become a way through.
MAX_BLOB = 64 << 20

# The DICOM JSON and XML models (PS3.18 Annex F, PS3.19 Annex A) carry a whole
# study — name, hospital number, date of birth, and the pixels in InlineBinary —
# as text. Every content rule above keys on binary structure, so a study written
# out by dcm2json was exempt as "text" and passed both gates. These match the
# models' own shape: an eight-hex-digit tag keying an object with a value
# representation.
DICOM_JSON = re.compile(rb'"[0-9A-Fa-f]{8}"\s*:\s*\{\s*"vr"\s*:')
DICOM_XML = re.compile(rb'<DicomAttribute[^>]*\btag\s*=')

# Encoded images, by magic. A frame lifted out of a real study to debug against
# is the likeliest way patient pixels enter *this* repository — it is the
# obvious move when a decoder mishandles one file, and the result is a picture
# of someone's chest with no header left to identify it as anything.
IMAGE_MAGIC = [
    (b"\xff\xd8\xff", "JPEG image"),
    (b"\x89PNG\r\n\x1a\n", "PNG image"),
    (b"BM", "BMP image"),
    (b"GIF8", "GIF image"),
    (b"II*\x00", "TIFF image"),
    (b"MM\x00*", "TIFF image"),
]

# ...except where this project's own test material lives. Both directories hold
# frames generated by conformance/generate.py or published under CC BY by the
# Imaging Data Commons, and both are listed here rather than inferred, so a
# frame saved anywhere else is refused by default.
IMAGE_ALLOWED = ("conformance/corpus/", "tests/data/")

# An archive hides its contents from a byte scan. Decompressing input from an
# untrusted source to look inside invites a decompression bomb, and nothing in
# this project needs an archive committed, so they are refused outright.
ARCHIVE_MAGIC = [
    (b"PK\x03\x04", "zip archive"),
    (b"PK\x05\x06", "empty zip archive"),
    (b"\x1f\x8b", "gzip stream"),
    (b"BZh", "bzip2 stream"),
    (b"\xfd7zXZ\x00", "xz stream"),
    (b"7z\xbc\xaf\x27\x1c", "7-zip archive"),
    (b"Rar!\x1a\x07", "rar archive"),
    (b"\x28\xb5\x2f\xfd", "zstd stream"),
]


def _git(*arguments: str) -> bytes:
    """Run git and return raw bytes — never `text=True`.

    Decoding git's output as text is what made non-ASCII paths invisible: git
    quotes them, the quoted form names no file, and the scan skipped them. Every
    caller here pairs this with `-z` and decodes each path itself.
    """
    return subprocess.run(("git",) + arguments,
                          capture_output=True, check=True).stdout


def _looks_like_text(data: bytes) -> bool:
    """Source and metadata are text. A renamed DICOM file is not.

    Judged over the whole content, not a sample of it. Sampling the first 64 KiB
    while searching 8 MiB for the UID meant a DICOM file behind 64 KiB of
    padding was declared text and exempted — the window that decides the
    exemption has to be the window the exemption covers.
    """
    if b"\x00" in data:
        return False
    try:
        data.decode("utf-8")
    except UnicodeDecodeError:
        return False
    return True


def _is_dicom_document(data: bytes) -> bool:
    """True for a study written out as JSON or XML — not for source quoting one.

    The pattern alone is not enough. This scanner's own test file carries a
    synthetic study as a literal so that the rule stays tested, and the first
    version of the rule refused the test that proves it works. Requiring the
    content to *be* such a document — first non-space byte `{`, `[` or `<` —
    separates the two, because that is what `dcm2json` and `dcm2xml` emit and
    what any tool reading one expects.
    """
    if not (DICOM_JSON.search(data) or DICOM_XML.search(data)):
        return False
    return data.lstrip()[:1] in (b"{", b"[", b"<")


def _allowed_image(names) -> bool:
    """True only if every name this content has ever had is test material.

    Every name, not any: a blob committed once under `conformance/corpus/` and
    once as `frame.jpg` at the root is the second one. Content with no name at
    all — a blob a tag points straight at — is not allowed, because the
    default when the scanner cannot tell has to be refusal.
    """
    if not names:
        return False
    return all(any(name.replace("\\", "/").startswith(prefix)
                   for prefix in IMAGE_ALLOWED) for name in names)


def verdict(name: str, head: bytes, names=None) -> str | None:
    """Why this content may not be committed under this name, or None.

    `name` contributes only its extension, and only ever to make the answer
    stricter — never to excuse content that would otherwise be refused, apart
    from the text-file case, which is itself checked against the bytes, and the
    test-material directories, which are checked against every path the content
    has ever had.
    """
    lowered = name.lower()
    for extension in MEDICAL:
        if lowered.endswith(extension):
            return "medical image extension"

    if head[128:132] == PREAMBLE:
        return "DICOM part-10 file"

    if head.startswith(LFS_POINTER):
        return ("git-lfs pointer — the real bytes are not in this history, "
                "so they cannot be checked")

    for magic, kind in ARCHIVE_MAGIC:
        if head.startswith(magic):
            return f"{kind} — its contents cannot be checked, so it is refused"
    if head[257:262] == b"ustar":
        return "tar archive — its contents cannot be checked, so it is refused"

    for magic, kind in IMAGE_MAGIC:
        if head.startswith(magic):
            if _allowed_image({name} if names is None else set(names)):
                break
            return (f"{kind} outside {' and '.join(IMAGE_ALLOWED)} — an image "
                    "lifted out of a study carries the picture without the "
                    "header that would identify it")

    if _is_dicom_document(head):
        return "DICOM JSON/XML model — a study in text form is still a study"

    if UID_STEM in head and not _looks_like_text(head):
        # Source, documentation and manifests name UIDs; that is their job,
        # and this project's do it constantly. What comes out of a scanner is
        # binary. Deciding on the bytes rather than the extension closes the
        # hole where a raw export called `notes.json` was exempt, and stops
        # the hook script — which quotes a UID and has no extension at all —
        # being reported as a patient file.
        return "contains a DICOM UID"

    return None


def staged() -> list[tuple[str, str, str]]:
    """Every path this commit introduces, with the blob git will actually store.

    Returns (path, mode, blob sha). Reading the sha rather than the path is the
    point: the pre-commit hook runs against the index, and the worktree is a
    different thing. Five ways they diverge were reproduced, four of them by
    accident rather than by attack — stage then delete, stage then edit, stage
    then replace with a symlink, and any `.gitattributes` clean filter.

    The filter is not `AM`. Git reports a file as `R` when it is similar enough
    to one that disappeared, and `--diff-filter=AM` skips those — so deleting
    `notes.cfg` and adding `scan.dcm` with the same bulk of bytes produced a
    rename, and a file named `.dcm` walked past this scanner untouched.
    """
    fields = _git("diff", "--cached", "--raw", "-z",
                  "--diff-filter=ACMRT").split(b"\x00")
    entries: list[tuple[str, str, str]] = []
    index = 0
    while index < len(fields):
        field = fields[index]
        if not field.startswith(b":"):
            index += 1
            continue
        parts = field.decode("utf-8", "replace").lstrip(":").split()
        # <mode-src> <mode-dst> <sha-src> <sha-dst> <status>
        mode, sha, status = parts[1], parts[3], parts[4]
        # A rename or copy is followed by two paths; the second is the new one.
        wanted = 2 if status[:1] in ("R", "C") else 1
        paths = fields[index + 1:index + 1 + wanted]
        index += 1 + wanted
        if paths:
            entries.append((paths[-1].decode("utf-8", "surrogateescape"), mode, sha))
    return entries


def _blob(sha: str) -> bytes | None:
    """The stored content of one blob, or None if it is too large to check."""
    size = int(_git("cat-file", "-s", sha).split()[0])
    if size > MAX_BLOB:
        return None
    return _git("cat-file", "blob", sha)


def scan_index() -> list[tuple[str, str]]:
    """Judge the blobs the commit will contain, under the paths it will use."""
    blocked = []
    for path, mode, sha in staged():
        if mode == "160000":
            # A submodule is a pointer, so no patient bytes enter this object
            # store — but `clone --recurse-submodules` fetches whatever it
            # points at, and this scanner cannot see there. Say so rather than
            # skip: a scan that cannot check something must not imply it did.
            blocked.append((path, "submodule — this scanner cannot see inside "
                                  "it, and a recursive clone will fetch it"))
            continue
        try:
            content = _blob(sha)
        except (subprocess.CalledProcessError, ValueError, IndexError) as error:
            blocked.append((path, f"unreadable, so unverifiable: {error}"))
            continue
        if content is None:
            blocked.append((path, f"larger than {MAX_BLOB >> 20} MiB, so it was "
                                  "not read in full and cannot be cleared"))
            continue
        why = verdict(path, content)
        if why:
            blocked.append((path, why))
    return blocked


def scan_worktree(paths) -> list[tuple[str, str]]:
    """Judge named files on disk — the `--paths` case, where disk is the point."""
    blocked = []
    for path in paths:
        if not os.path.isfile(path):
            blocked.append((path, "not a readable file, so it was not checked"))
            continue
        try:
            with open(path, "rb") as handle:
                content = handle.read(MAX_BLOB + 1)
        except OSError as error:
            blocked.append((path, f"unreadable, so unverifiable: {error}"))
            continue
        if len(content) > MAX_BLOB:
            blocked.append((path, f"larger than {MAX_BLOB >> 20} MiB, so it was "
                                  "not read in full and cannot be cleared"))
            continue
        why = verdict(path, content)
        if why:
            blocked.append((path, why))
    return blocked


def _every_blob() -> list[str]:
    """Every blob a fetch could reach, plus everything the reflog can restore.

    Two things this deliberately is and is not:

    * It includes `--reflog`, so an old stash entry or a commit dropped by
      `reset --hard` or `--amend` is still examined. Those are recoverable
      and were invisible to a plain `--all`.
    * It reads shas rather than indexing by path. A tag can point straight at
      a blob, which then has no filename — and the previous version keyed the
      whole scan on the path, so that blob was never read at all.

    It stops short of `--batch-all-objects`, which also reports loose objects
    no ref or reflog can reach. Those never leave the machine — `git push`
    sends reachable objects only — and reporting them means reporting every
    experiment anyone has ever abandoned.
    """
    out = _git("rev-list", "--objects", "--all", "--reflog", "--remotes")
    shas = [line.split()[0].decode() for line in out.splitlines() if line.strip()]
    if not shas:
        return []
    kinds = subprocess.run(
        ["git", "cat-file", "--batch-check=%(objecttype) %(objectname)"],
        input="\n".join(shas).encode(), capture_output=True, check=True).stdout
    return [line.split()[1].decode() for line in kinds.splitlines()
            if line.startswith(b"blob ")]


def _blob_names() -> dict[str, set[str]]:
    """Every full path each blob has ever been committed under.

    A blob keeps one identity and can have many names. Recording only the
    latest let a file committed as `scan.dcm` and renamed to `notes.txt`
    afterwards be judged under the harmless name for ever.

    Full paths, from `ls-tree -r` per commit rather than a bare `ls-tree` per
    tree: the directory a file sits in is what decides whether an image is this
    project's own test material, and a basename cannot answer that.
    """
    commits = [line.split()[0].decode()
               for line in _git("rev-list", "--all", "--reflog", "--remotes").splitlines()
               if line.strip()]
    names: dict[str, set[str]] = {}
    for commit in commits:
        entries = _git("ls-tree", "-r", "-z", "--full-tree", commit)
        for entry in entries.split(b"\x00"):
            if not entry:
                continue
            head, _, name = entry.partition(b"\t")
            parts = head.split()
            if len(parts) >= 3 and parts[1] == b"blob" and name:
                names.setdefault(parts[2].decode(),
                                 set()).add(name.decode("utf-8", "surrogateescape"))
    return names


def scan_history() -> list[tuple[str, str]]:
    """Every blob in the repository, under every name it has ever carried.

    Rewriting history does not remove a blob from a remote that has already
    seen it, so this is the check that has to be right.
    """
    blobs = _every_blob()
    if not blobs:
        return []
    names = _blob_names()

    blocked = []
    batch = subprocess.Popen(["git", "cat-file", "--batch"],
                             stdin=subprocess.PIPE, stdout=subprocess.PIPE)
    try:
        for sha in blobs:
            batch.stdin.write((sha + "\n").encode())
            batch.stdin.flush()
            header = batch.stdout.readline().split()
            if len(header) < 3:
                # Unreadable object. Refuse rather than skip: a scan that
                # cannot see something must not report that it saw nothing.
                blocked.append((sha, "could not be read, so could not be checked"))
                continue
            size = int(header[2])
            body = batch.stdout.read(size)
            batch.stdout.read(1)                        # trailing newline
            aliases = sorted(names.get(sha, set()))
            if size > MAX_BLOB:
                blocked.append((aliases[0] if aliases else sha,
                                f"larger than {MAX_BLOB >> 20} MiB, so it was "
                                "not read in full and cannot be cleared"))
                continue
            reasons = [why for why in
                       (verdict(name, body, aliases) for name in (aliases or [sha]))
                       if why]
            if reasons:
                # Report every name the blob has carried, not the first that
                # matched. Whoever has to find and purge it needs the name it
                # was committed under, which is rarely the one it has now.
                where = aliases[0] if aliases else sha
                if len(aliases) > 1:
                    where = f"{where}  (also: {', '.join(aliases[1:])})"
                blocked.append((f"{where}  ({sha[:10]})", reasons[0]))
    finally:
        batch.stdin.close()
        if batch.wait() != 0:
            blocked.append(("git cat-file", "exited non-zero; the scan is incomplete"))
    return blocked


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--history", action="store_true",
                        help="scan every blob ever committed, not the index")
    parser.add_argument("--paths", nargs="*", help="scan these files")
    args = parser.parse_args()

    if args.history:
        blocked, scope = scan_history(), "this repository's history"
    elif args.paths:
        blocked, scope = scan_worktree(args.paths), "the files named"
    else:
        blocked, scope = scan_index(), "the files being committed"

    if not blocked:
        return 0

    print(f"\nRefused. These files in {scope} look like medical images:\n",
          file=sys.stderr)
    for path, why in blocked:
        print(f"  {path}  ({why})", file=sys.stderr)
    print("\nPatient data must never enter this repository, and rewriting\n"
          "history after a push does not remove it from a remote.\n"
          "\n"
          "If you are certain a file is synthetic, commit it with --no-verify\n"
          "and say so in the message — then check `git status` first. A file\n"
          "refused here stays staged, and the next --no-verify will take it.\n",
          file=sys.stderr)
    return 1


if __name__ == "__main__":
    # A refusal names the file you have to go and deal with, so the name has to
    # survive being printed. Python's stderr escapes anything the console
    # encoding cannot represent, which on a Thai Windows console turned
    # `ผู้ป่วย/scan.dcm` into `ผู...` — a correct refusal that does
    # not tell you which file to remove.
    for stream in (sys.stdout, sys.stderr):
        try:
            stream.reconfigure(encoding="utf-8", errors="backslashreplace")
        except (AttributeError, ValueError):        # not a real console
            pass

    try:
        sys.exit(main())
    except Exception as error:                  # never fail open
        print(f"\nThe medical-image scan could not run: {error!r}\n"
              "Refusing rather than allowing an unchecked commit.\n",
              file=sys.stderr)
        sys.exit(2)
